import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/homepage/footer";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`max-w-screen-2xl mx-auto font-inter ${inter.className}`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
